require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "*.gemspec"
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "storage/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case
