name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests_rails:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2']
        rails_version: [6.1.7.8, 7.0.8.4]
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
